"""Construye un visor HTML a partir de las evidencias, sin inventar resultados."""
from pathlib import Path
import html,json,xml.etree.ElementTree as ET
P=Path(__file__).resolve().parents[1];E=P/'evidencias'
def read(name):return (E/name).read_text()
def esc(s):return html.escape(s)
root=ET.fromstring(read('pytest.xml')); suite=root if root.tag=='testsuite' else root.find('testsuite')
count=int(suite.attrib['tests']);failed=int(suite.attrib['failures'])+int(suite.attrib['errors'])
http=json.loads(read('http-real.json')); http_n=sum(r['passed'] for r in http['results'])
newman=[json.loads(read(f'newman-{port}.json')) for port in (5000,5001,5002)]
newman_n=sum(d['run']['stats']['assertions']['total'] for d in newman)
newman_f=sum(d['run']['stats']['assertions']['failed'] for d in newman)
persist=json.loads(read('persistencia.json'))
assert all(m.get('passed') for m in persist['markers'].values()),'Debe completarse la prueba antes de generar el informe'
rows=''.join(f'<tr><td>{esc(label)}</td><td>{m["book"]["id"]}</td><td>Creado (201)</td><td>{m["after_status"]}</td><td class="ok">Correcto</td></tr>' for label,m in persist['markers'].items())
newrows=''.join(f'<tr><td>{port}</td><td>{d["run"]["stats"]["requests"]["total"]}</td><td>{d["run"]["stats"]["assertions"]["total"]}</td><td class="ok">{d["run"]["stats"]["assertions"]["failed"]} fallos</td></tr>' for port,d in zip((5000,5001,5002),newman))
page='''<!doctype html><html lang="es"><meta charset="utf-8"><title>Práctica REST · Evidencias del equipo</title><style>
*{box-sizing:border-box}body{margin:0;font:16px system-ui,sans-serif;color:#142b43;background:#f2f5f9}header{background:#132b45;color:#fff;padding:18px 30px}header small{color:#8adfc6;letter-spacing:2px}h1{font-size:32px;margin:8px 0}header p{margin:5px 0;color:#d4dfeb}nav{display:flex;gap:8px;background:white;padding:10px 30px;border-bottom:1px solid #d7e1e9}button{border:1px solid #bccdda;background:#fff;color:#173551;border-radius:7px;padding:10px 17px;font-weight:650;cursor:pointer}button.active{background:#176b65;color:white;border-color:#176b65}main{max-width:1240px;padding:18px 30px;margin:auto}h2{font-size:24px;margin:0 0 15px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,article{background:white;border:1px solid #dbe4ec;border-radius:12px;padding:16px}.card strong{font-size:36px;display:block;color:#14695e}.card span{font-size:15px;color:#536c7f}article{margin-top:20px}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;padding:9px 12px;border-bottom:1px solid #e5eaf0}th{background:#f3f6fa}.ok{color:#067351;font-weight:700}.pending{background:#fff3d8;color:#745109;padding:15px 19px;border-radius:8px;margin-top:20px}pre{font:11px/1.3 ui-monospace,SFMono-Regular,monospace;background:#14283c;color:#d6e9f4;padding:14px;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere}.muted{color:#587086;font-size:14px}.panel{display:none}.panel.active{display:block}footer{margin-top:18px;font-size:13px;color:#577084}a{color:#08766b}
</style><header><small>COMPUTACIÓN EN LA NUBE · INFORME DE EVIDENCIAS</small><h1>REST + MySQL + IoT</h1><p>Natalia Hernández Piedrahita · Miguel Ángel Diuza · Juan Ospina Tenorio</p><p>24 septiembre 2026 · Ubuntu 22.04 ARM64 · Vagrant / VirtualBox</p></header><nav>'''
for i,label in enumerate(['Resumen','MySQL','Persistencia','Postman','curl','Pruebas Python']):page+=f'<button class="{"active" if i==0 else ""}" onclick="show({i})">{label}</button>'
page+='</nav><main>'
page+=f'''<section class="panel active"><h2>Resultados comprobados</h2><div class="cards"><div class="card"><strong>{count-failed}/{count}</strong><span>Pruebas automáticas Python</span></div><div class="card"><strong>{http_n}/{http_n}</strong><span>Respuestas HTTP reales correctas</span></div><div class="card"><strong>{newman_n-newman_f}/{newman_n}</strong><span>Aserciones Postman / Newman</span></div></div><article><table><tr><th>Implementación</th><th>Almacenamiento</th><th>Resultado</th></tr><tr><td>Python Flask · puerto 5000</td><td>Memoria del proceso</td><td class="ok">CRUD verificado</td></tr><tr><td>Python Flask · puerto 5001</td><td>MySQL 8.0.46</td><td class="ok">CRUD y persistencia verificados</td></tr><tr><td>Desafío JavaScript · puerto 5002</td><td>MySQL compartido</td><td class="ok">CRUD y persistencia verificados</td></tr></table></article><div class="pending"><b>Ubidots: pendiente de cuenta.</b> Simulador de cinco variables y pruebas locales listos. Recepción, dashboard y correo todavía sin verificar.</div><p class="muted">Este panel presenta registros de ejecución locales. No es un dashboard de Ubidots.</p></section>'''
page+=f'<section class="panel"><h2>Inspección directa de MySQL</h2><p>Base aislada <b>rest_equipo</b> · Tabla <b>books</b> · Consulta ejecutada dentro de Ubuntu</p><pre>{esc(read("mysql-tabla.txt"))}</pre></section>'
page+=f'''<section class="panel"><h2>Persistencia después de apagar y encender Ubuntu</h2><article><table><tr><th>Implementación</th><th>ID</th><th>Antes</th><th>Después</th><th>Verificación</th></tr>{rows}</table><p><b>Memoria:</b> el registro desaparece (404). <b>MySQL:</b> ambos registros sobreviven íntegros (200).</p></article><pre>{esc(read('vm-apagada.txt'))}</pre><p class="muted">Antes: {persist['before_utc']}<br>Después: {persist['after_utc']}</p><p>Se apagó la VM de forma ordenada. No se borró el disco ni se destruyó la máquina.</p></section>'''
page+=f'''<section class="panel"><h2>Colección Postman ejecutada con Newman</h2><p>Ocho peticiones por servicio: consulta, creación, actualización, validación y eliminación.</p><article><table><tr><th>Puerto</th><th>Peticiones</th><th>Aserciones</th><th>Resultado</th></tr>{newrows}</table></article><pre>{esc(chr(10).join(read('newman-5001.txt').splitlines()[-20:]))}</pre><p class="muted">Prueba realizada con Newman, ejecutor oficial de Postman; no corresponde a su interfaz gráfica.</p></section>'''
page+=f'<section class="panel"><h2>Pruebas reales con curl · MySQL</h2><pre>{esc(read("curl-mysql.txt"))}</pre></section>'
page+=f'<section class="panel"><h2>Pruebas automáticas Python</h2><p>Validación del CRUD, errores, memoria y contrato del simulador IoT.</p><pre>{esc(read("pytest.txt"))}</pre></section>'
page+='''<footer>Fuentes auditables: archivos originales JSON, XML y TXT de la carpeta evidencias del repositorio.</footer></main><script>function show(n){document.querySelectorAll('.panel').forEach((x,i)=>x.classList.toggle('active',i===n));document.querySelectorAll('button').forEach((x,i)=>x.classList.toggle('active',i===n));history.replaceState(null,'','#'+n)}if(location.hash)show(Number(location.hash.slice(1))||0)</script></html>'''
(P/'docs/panel-evidencias.html').write_text(page)
print('Panel generado desde evidencias verificadas')
